# Generated by Django 5.0.4 on 2024-05-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesexternas',
            name='has_answered',
            field=models.BooleanField(default=False, verbose_name='Respondido'),
        ),
    ]
