# Generated by Django 5.0.4 on 2024-06-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorios',
            name='campus_location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación del Campus'),
        ),
    ]
