# Generated by Django 5.0.4 on 2024-06-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_laboratorios_campus_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position_company',
            field=models.CharField(default='Usuario UniCLab', max_length=150, verbose_name='Cargo'),
        ),
    ]
