# Generated by Django 5.0.4 on 2024-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0003_user_position_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position_company',
            field=models.CharField(max_length=150, verbose_name='Cargo'),
        ),
    ]
