# Generated by Django 5.0.4 on 2024-06-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0007_alter_solicitudesexternas_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='formato_libre',
            field=models.FileField(blank=True, null=True, upload_to='formato_etiquetas/'),
        ),
    ]
