# Generated by Django 5.0.4 on 2024-06-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0002_frases_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sustancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cas', models.CharField(blank=True, max_length=40, null=True)),
                ('phrase_h', models.ManyToManyField(blank=True, to='etiquetas.frases_h')),
                ('warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiquetas.advertencia')),
            ],
        ),
    ]
