# Generated by Django 5.0.4 on 2024-06-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0003_sustancias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertencia',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='frases_h',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sustancias',
            name='cas',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='CAS'),
        ),
        migrations.AlterField(
            model_name='sustancias',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sustancias',
            name='phrase_h',
            field=models.ManyToManyField(blank=True, to='etiquetas.frases_h', verbose_name='Frases H'),
        ),
        migrations.AlterField(
            model_name='sustancias',
            name='warning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiquetas.advertencia', verbose_name='Advertencia'),
        ),
    ]
