# Generated by Django 5.0.4 on 2024-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0006_frases_p_sustancias_phrase_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('pictogram', models.ImageField(upload_to='pictogramas/', verbose_name='Pictograma')),
            ],
            options={
                'verbose_name': 'Pictograma',
                'verbose_name_plural': 'Pictogramas',
            },
        ),
    ]
