# Generated by Django 5.0.4 on 2024-08-03 14:14

import etiquetas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0008_sustancias_pictogram_clp1_sustancias_pictogram_clp2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictograma',
            name='pictogram',
            field=models.ImageField(upload_to='pictogramas/', validators=[etiquetas.models.validate_image_extension, etiquetas.models.validate_image_size, etiquetas.models.validate_image_dimensions], verbose_name='Pictograma'),
        ),
    ]
