# Generated by Django 5.0.4 on 2024-08-03 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0009_alter_pictograma_pictogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pictograma',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_pictogramas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='pictograma',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación'),
        ),
        migrations.AddField(
            model_name='pictograma',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activo', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pictograma',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='pictograma',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_pictogramas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
