# Generated by Django 5.0.4 on 2024-05-31 17:19

import django.core.validators
import django.db.models.deletion
import residuos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reactivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CERTIFICADO_DISPOSICION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Descripción breve')),
                ('date', models.DateField(verbose_name='Fecha de Certificación')),
                ('attach', models.FileField(upload_to='certificados_finales/', validators=[django.core.validators.FileExtensionValidator(['pdf']), residuos.models.validate_file_size], verbose_name='Adjunto (Archivos PDF, máximo 2MB.)')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Activo', verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_certificadodisposicion', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_certificadodisposicion', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Certificado de Disposición',
                'verbose_name_plural': 'Certificados de Disposición',
            },
        ),
        migrations.CreateModel(
            name='CLASIFICACION_RESIDUOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Máximo 10 caracteres', max_length=10, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Máximo 500 caracteres', max_length=500, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Activo', verbose_name='Activo')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_clasificacion', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_clasificacion', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Clasificación de Residuos',
                'verbose_name_plural': 'Clasificaciones de Residuos',
            },
        ),
        migrations.CreateModel(
            name='FichaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de Ficha o Proveedor')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Activo', verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_fichaseguiridad', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_fichaseguiridad', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Ficha de Seguridad',
                'verbose_name_plural': 'Fichas de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='InformacionInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Breve descripción o Título')),
                ('tipo', models.CharField(choices=[('Video de Youtube', 'Video de Youtube'), ('Enlace Externo', 'Enlace Externo')], max_length=20, verbose_name='Tipo')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('id_youtube', models.CharField(blank=True, max_length=500, null=True, verbose_name='Id Youtube')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Activo', verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_enlaces', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_enlaces', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Información de Interés',
                'verbose_name_plural': 'Información de Interés',
            },
        ),
        migrations.CreateModel(
            name='SOLICITUD_RESIDUO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sol', max_length=14)),
                ('leido', models.BooleanField(default=False, help_text='Leído', verbose_name='Leído')),
                ('respondido', models.BooleanField(default=False, help_text='Respondido', verbose_name='Respondido')),
                ('is_active', models.BooleanField(default=True, help_text='Activo', verbose_name='Activo')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_solicitud_residuo', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_solicitud_residuo', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Registro de Residuo',
                'verbose_name_plural': 'Registros de Residuos',
            },
        ),
        migrations.CreateModel(
            name='REGISTRO_RESIDUOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(choices=[('Area', 'ÁREA'), ('Laboratorio', 'LABORATORIO')], max_length=11, verbose_name='Dependencia')),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_residuo', models.CharField(max_length=400, verbose_name='Nombre del Residuo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('numero_envases', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Número de Envases')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('residuo_enviado', models.BooleanField(default=False, help_text='Estado de envío de solicitud al servidor', verbose_name='Estado de envío')),
                ('is_active', models.BooleanField(default=True, help_text='Activo', verbose_name='Activo')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('total_residuo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total')),
                ('clasificado', models.ManyToManyField(blank=True, to='residuos.clasificacion_residuos', verbose_name='Clasificado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_registro', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.estados', verbose_name='Estado')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reactivos.laboratorios')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_registro', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('unidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.unidades', verbose_name='Unidades')),
                ('registro_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_residuos', to='residuos.solicitud_residuo')),
            ],
            options={
                'verbose_name': 'Registro de Residuos',
                'verbose_name_plural': 'Registros de Residuos',
            },
        ),
    ]
