# Generated by Django 5.0.4 on 2024-04-17 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLASIFICACION_RESIDUOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Máximo 10 caracteres', max_length=10, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Máximo 500 caracteres', max_length=500, verbose_name='Descripción')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_clasificacion', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_clasificacion', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Clasificación de Residuos',
                'verbose_name_plural': 'Clasificaciones de Residuos',
            },
        ),
    ]
