# Generated by Django 5.0.4 on 2024-04-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion_residuos',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='clasificacion_residuos',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización'),
        ),
    ]
