# Generated by Django 5.0.4 on 2024-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0002_alter_clasificacion_residuos_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion_residuos',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activo', verbose_name='Activo'),
        ),
    ]
