# Generated by Django 5.0.4 on 2024-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0004_registro_residuos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_residuos',
            name='nombre_residuo',
            field=models.CharField(max_length=400, verbose_name='Nombre del Residuo'),
        ),
    ]
