# Generated by Django 5.0.4 on 2024-04-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0008_alter_registro_residuos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_residuos',
            name='clasificado',
            field=models.ManyToManyField(blank=True, to='residuos.clasificacion_residuos', verbose_name='Clasificado'),
        ),
    ]
