# Generated by Django 5.0.4 on 2024-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0009_alter_registro_residuos_clasificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_residuos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
    ]
