# Generated by Django 5.0.4 on 2024-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0010_registro_residuos_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_residuos',
            name='dependencia',
            field=models.CharField(choices=[('Area', 'ÁREA'), ('Laboratorio', 'LABORATORIO')], max_length=11, verbose_name='Dependencia'),
        ),
    ]
