# Generated by Django 5.0.4 on 2024-04-24 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0012_alter_registro_residuos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_residuos',
            name='numero_envases',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Número de Envases'),
        ),
    ]
