# Generated by Django 5.0.4 on 2024-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0013_alter_registro_residuos_numero_envases'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_residuos',
            name='total_residuo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total'),
        ),
    ]
