# Generated by Django 5.0.4 on 2024-05-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0014_registro_residuos_total_residuo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_residuos',
            name='ficha_seguridad',
            field=models.FileField(blank=True, null=True, upload_to='fichas_seguridad/', verbose_name='Ficha de Seguridad'),
        ),
    ]
