# Generated by Django 5.0.4 on 2024-05-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0015_registro_residuos_ficha_seguridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_residuos',
            name='ficha_seguridad',
        ),
    ]
