# Generated by Django 5.0.4 on 2024-05-11 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0016_remove_registro_residuos_ficha_seguridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='FICHAS_SEGUIRDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Fichas de seguiridad')),
                ('registro_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos_residuos', to='residuos.registro_residuos')),
            ],
        ),
    ]
