# Generated by Django 5.0.4 on 2024-05-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0017_fichas_seguirdad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FICHAS_SEGUIRDAD',
            new_name='FICHAS_SEGURIDAD',
        ),
    ]
