# Generated by Django 5.0.4 on 2024-05-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0018_rename_fichas_seguirdad_fichas_seguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichas_seguridad',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='fichas_seguridad',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Ficha de seguiridad'),
        ),
    ]
