# Generated by Django 5.0.4 on 2024-05-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0019_fichas_seguridad_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_residuos',
            name='residuo_enviado',
            field=models.BooleanField(default=False, help_text='Estado de envío de solicitud al servidor', verbose_name='Estado de envío'),
        ),
    ]
