# Generated by Django 5.0.4 on 2024-05-15 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0020_registro_residuos_residuo_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOLICITUD_RESIDUO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Activo', verbose_name='Activo')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createby_solicitud_residuo', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_solicitud_residuo', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('registro_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_residuos', to='residuos.registro_residuos')),
            ],
            options={
                'verbose_name': 'Registro de Residuo',
                'verbose_name_plural': 'Registros de Residuos',
            },
        ),
    ]
