# Generated by Django 5.0.4 on 2024-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0022_remove_solicitud_residuo_registro_residuo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_residuo',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
