# Generated by Django 5.0.4 on 2024-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0023_solicitud_residuo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_residuo',
            name='name',
            field=models.CharField(blank=True, default='Sol', max_length=10, null=True),
        ),
    ]
