# Generated by Django 5.0.4 on 2024-05-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0026_alter_solicitud_residuo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_residuo',
            name='leido',
            field=models.BooleanField(default=True, help_text='Activo', verbose_name='Activo'),
        ),
    ]
