# Generated by Django 5.0.4 on 2024-05-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0027_solicitud_residuo_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_residuo',
            name='leido',
            field=models.BooleanField(default=False, help_text='Activo', verbose_name='Activo'),
        ),
    ]
