# Generated by Django 5.0.4 on 2024-05-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0028_alter_solicitud_residuo_leido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FICHAS_SEGURIDAD',
        ),
    ]
