# Generated by Django 5.0.4 on 2024-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0029_delete_fichas_seguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_residuo',
            name='respondido',
            field=models.BooleanField(default=False, help_text='Respondido', verbose_name='Respondido'),
        ),
        migrations.AlterField(
            model_name='solicitud_residuo',
            name='leido',
            field=models.BooleanField(default=False, help_text='Leído', verbose_name='Leído'),
        ),
    ]
