# Generated by Django 5.0.4 on 2024-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0031_fichaseguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaseguridad',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre de Ficha o Proveedor'),
        ),
        migrations.AlterField(
            model_name='fichaseguridad',
            name='url',
            field=models.URLField(max_length=500, unique=True, verbose_name='URL'),
        ),
    ]
