# Generated by Django 5.0.4 on 2024-05-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0032_alter_fichaseguridad_name_alter_fichaseguridad_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaseguridad',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activo', verbose_name='Activo'),
        ),
    ]
