# Generated by Django 5.0.4 on 2024-05-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0035_alter_certificado_disposicion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioninteres',
            name='url',
            field=models.URLField(max_length=500, unique=True, verbose_name='URL'),
        ),
    ]
