# Generated by Django 5.0.4 on 2024-05-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0036_alter_informacioninteres_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioninteres',
            name='tipo',
            field=models.CharField(choices=[('Video de Youtube', 'Video de Youtube'), ('Enlace Externo', 'Enlace Externo')], max_length=20, verbose_name='Tipo'),
        ),
    ]
