# Generated by Django 5.0.4 on 2024-05-28 22:21

import django.core.validators
import residuos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0037_alter_informacioninteres_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioninteres',
            name='id_youtube',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Id Youtube'),
        ),
        migrations.AlterField(
            model_name='certificado_disposicion',
            name='attach',
            field=models.FileField(upload_to='certificados_finales/', validators=[django.core.validators.FileExtensionValidator(['pdf']), residuos.models.validate_file_size], verbose_name='Adjunto (Archivos PDF, máximo 2MB.)'),
        ),
    ]
